services:
  billing-services:
    container_name: "api-gateway"
    build: .
    networks:
      - java-project
    env_file:
      - .env
    ports:
      - "4000:4000"
    restart: unless-stopped

networks:
  java-project:
    external: true