services:
  auth-services:
    build: .
    container_name: "auth-services"
    env_file:
      - .env
    ports:
      - "4001:4000"
    networks:
      - java-project
    restart: unless-stopped

networks:
  java-project:
    external: true
